name: Import from leetcode
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Maybe download LeetCode index (weekly cache)
        run: |
          set -e
          week_start=$(date -u -d 'monday this week 00:00' +%s)
          if [ -f import/leetcode.json ]; then
            mtime=$(stat -c %Y import/leetcode.json)
          else
            mtime=0
          fi
          if [ "$mtime" -ge "$week_start" ]; then
            echo "LeetCode index is fresh. Skip download."
          else
            echo "Downloading fresh LeetCode index..."
            curl -fsSL --retry 3 --retry-delay 2 \
                 -H "Referer: https://leetcode.com/" \
                 -H "Accept: application/json" \
                 --create-dirs -o import/leetcode.json \
                 https://leetcode.com/api/problems/all/
          fi

      - run: python import/leetcode.py

      - name: Commit changes (Import solution #<ids>)
        run: |
          if [ -z "$(git status --porcelain)" ]; then
            echo "Nothing to commit"
            exit 0
          fi
      
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add -A
      
          files="$(git diff --cached --name-only)"
          probs="$(printf "%s\n" "$files" \
            | grep -Eo 'code/[^/]+/[0-9]+\.' | grep -Eo '[0-9]+' \
            | sort -n | uniq | paste -sd, -)"
          if [ -n "$probs" ]; then
            msg="Import solution #$probs"
          else
            base="$(printf "%s\n" "$files" | xargs -n1 basename | paste -sd ", " -)"
            msg="Update $base"
          fi
      
          git commit -m "$msg"
          git push
